name: Bug Report
description: Create a report to help us improve
title: '[BUG] '
labels: ['bug']
assignees: ['BuchiNy']
body:
  - type: markdown
    attributes:
      value: |
        This bug report is used to report any problems that Fabla has encountered. Please complete the form below, and we will begin investigating the issue. Thank you :)

  - type: textarea
    id: description
    attributes:
      label: Description of the problem
      description: Please describe the problem that is happening.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please tell us exactly how to reproduce the problem that you encountered.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected-results
    attributes:
      label: Expected results
      description: Please tell us what is expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-results
    attributes:
      label: Actual results
      description: Please tell us what is actually happening.
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: 'e.g. iPhone 12, Pixel 5'

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
      - iOS
      - Android
      - iOS & Android

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
