# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Sample code for iOS, just keeping here because i am too lazy to create fastlan file in the iOS folder
# platform :ios do
#     desc" Build and Deploy to firebase app distribution"
#     lane :iOS_deploy_to_firebase do
#         #generate release note for the build
#         release_notes = generate_release_notes
#         # Use Flutter to build the app
#         sh("flutter build ipa --debug --build-name=1.0.#{ENV['GITHUB_RUN_NUMBER'] || '1'} --build-number=#{ENV['GITHUB_RUN_NUMBER'] || '1'}")
#         firebase_app_distribution(
#             app: ENV["FIREBASE_IOS_APP_ID"].strip,
#             groups: "testers",
#             firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"].strip,
#             service_credentials_file: ENV["CREDENTIAL_FILE_CONTENT"],
#             ios_artifact_path: "../build/ios/ipa/Runner.ipa",
#             ios_artifact_type: "IPA",
#             debug: true,
#             upload_timeout: 600, # 10 minutes
#             release_notes: release_notes
#         )
#     end

default_platform(:android)

platform :android do
  desc "Build and Deploy to firebase app distribution"
  lane :deploy_to_firebase do
      #generate release note for the build
       release_notes = generate_release_notes
       # Use Flutter to build the app
       sh("flutter build apk --debug --build-name=1.0.#{ENV['GITHUB_RUN_NUMBER'] || '1'} --build-number=#{ENV['GITHUB_RUN_NUMBER'] || '1'}")
      firebase_app_distribution(
           app: ENV["FIREBASE_APP_ID"].strip,
           groups: "testers",
           firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"].strip,
           service_credentials_file: ENV["CREDENTIAL_FILE_CONTENT"],
           android_artifact_path: "../build/app/outputs/flutter-apk/app-debug.apk",
           android_artifact_type: "APK",
           debug: true,
           upload_timeout: 600, # 10 minutes
           release_notes: release_notes
         )
  end
    # Helper method to generate release notes
    private_lane :generate_release_notes do
      # Read from file and add build info
      base_notes = File.exist?("../release_notes.txt") ? File.read("../release_notes.txt") : "No release notes provided."

      build_info = "\n\n🔨 Build Info:\n"
      build_info += "- Build ##{ENV['GITHUB_RUN_NUMBER'] || '1'}\n"
      build_info += "- Branch: #{ENV['GITHUB_REF_NAME'] || 'unknown'}\n"
      build_info += "- Built on: #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}"

      base_notes + build_info
    end
end
